#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : neutron-lib
Version  : 1.18.0
Release  : 13
URL      : https://files.pythonhosted.org/packages/1d/62/347baad0aaf1ee1e62d0d5b54bae3d442da8813dba083e133b0143afc63f/neutron-lib-1.18.0.tar.gz
Source0  : https://files.pythonhosted.org/packages/1d/62/347baad0aaf1ee1e62d0d5b54bae3d442da8813dba083e133b0143afc63f/neutron-lib-1.18.0.tar.gz
Summary  : Neutron shared routines and utilities
Group    : Development/Tools
License  : Apache-2.0
Requires: neutron-lib-python3
Requires: neutron-lib-license
Requires: neutron-lib-python
Requires: SQLAlchemy
Requires: Sphinx
Requires: WebOb
Requires: keystoneauth1
Requires: openstackdocstheme
Requires: os-api-ref
Requires: oslo.concurrency
Requires: oslo.config
Requires: oslo.context
Requires: oslo.db
Requires: oslo.i18n
Requires: oslo.log
Requires: oslo.messaging
Requires: oslo.policy
Requires: oslo.serialization
Requires: oslo.service
Requires: oslo.utils
Requires: oslo.versionedobjects
Requires: osprofiler
Requires: pbr
Requires: pecan
Requires: python-mock
Requires: reno
Requires: six
Requires: stevedore
Requires: weakrefmethod
BuildRequires : buildreq-distutils3
BuildRequires : pbr

%description
Team and repository tags
        ========================

%package license
Summary: license components for the neutron-lib package.
Group: Default

%description license
license components for the neutron-lib package.


%package python
Summary: python components for the neutron-lib package.
Group: Default
Requires: neutron-lib-python3

%description python
python components for the neutron-lib package.


%package python3
Summary: python3 components for the neutron-lib package.
Group: Default
Requires: python3-core

%description python3
python3 components for the neutron-lib package.


%prep
%setup -q -n neutron-lib-1.18.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1533908535
python3 setup.py build -b py3

%install
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/doc/neutron-lib
cp LICENSE %{buildroot}/usr/share/doc/neutron-lib/LICENSE
python3 -tt setup.py build -b py3 install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(-,root,root,-)
/usr/share/doc/neutron-lib/LICENSE

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
